spring:
  datasource:
    url: jdbc:mysql://localhost:3306/WRM
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081


#attributes for the application WRM

waitingList:
  algorithm: FIFO
  capacity: 16


algorithms:
  - name: FIFO
    class: SomeClass
  - name: PR
    class: SomeClass
  - name: SJF
    class: SomeClass
