services:
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: WRM
      MYSQL_ROOT_PASSWORD : root1234
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root1234
    ports:
      - "8080:80"
    networks:
      - app-network



volumes:
  my-db:

networks:
  app-network:
    driver: bridge
